ft2m = 0.3048;
lbs2kg = 0.4536;
kts2mps = 0.5144;
in2m = 0.0254;

% For test
whichone = 'test';
m_fuel = 4100*lbs2kg;       % Fuel mass [lbs]->[kg]

% % For reference
% whichone = 'reference';
% m_fuel = 4050*lbs2kg;       % Fuel mass [lbs]->[kg]

load(strcat(whichone,'_payload.mat'));
m_PL = sum(PL.data(:,1));   % Payload mass [kg]
% Shift of cg, 3L from 288 to 134
x_shift = 134-288;          % 3L moves forward to cockpit [in]

load('fuel_moment.mat');
fuel_moment.data(:,1) = fuel_moment.data(:,1)*lbs2kg;       % Fuel mass [lbs]->[kg]
fuel_moment.data(:,2) = fuel_moment.data(:,2)*lbs2kg;       % Fuel moment [in*lbs]-[in*kg]
linear_fuel = polyfit(fuel_moment.data(:,1), fuel_moment.data(:,2), 1); % Input [kg], output [in*kg]

lambda = -6.5e-3;   % [k/m]
T0 = 273.15+15;     % [K]
p0 = 101325;        % [Pa]
rho0 = 1.225;       % [kg/m^3]
gamma = 1.4;
R = 287.05;         % [J/kg/K]
g = 9.81;           % [m/s^2]

S_wing = 30;                % Total area of the wing [m^2]
b_wing = 15.911;            % wing span [m]
A = b_wing^2/S_wing;        % wing aspect ratio
MAC = 2.0569;               % mean aerodynamic cord [m]
m_OE = 9165*lbs2kg;         % Operational empty mass [lbs]->[kg]
x_cg_OE = 291.65;           % cg location of empty a/c [in], assume to be 0.25c
LEMAC = x_cg_OE*in2m-MAC/4; % Leading edge of MAC from datum
m_init = m_OE+m_PL+m_fuel;  % Initial mass of a/c+fuel+pl [kg]
D_engine = 27*in2m;         % Engine diameter [m]
CmTc = -0.0064;             % Thrust moment arm
Ws = 60500;                 % Standard a/c weight [N]
FLs = 0.048;                % Standard fuel flow [kg/s]

% Get timestamps for series1
load(strcat(whichone, '_data.mat'));
dt = 0.1;
load(strcat(whichone, '_series1.mat'));
i_series1 = int32((postdata.data(:,1)-flightdata.time.data(1))/dt+1);


% % Generate a matlab.dat for thrust.exe
% % Assume engine is aligned with a/c body x-axis
% % The intake air is alpha to the engine, so V_intake=TAS*cos(alpha)
% hp = flightdata.Dadc1_alt.data(i_series1)*ft2m;                   % Pressure Altitude [ft]->[m]
% alpha = deg2rad(flightdata.vane_AOA.data(i_series1));             % AOA [rad]
% mach = flightdata.Dadc1_mach.data(i_series1).*cos(alpha);         % Mach axially to engine
% T_static = 273.15+flightdata.Dadc1_sat.data(i_series1);           % Static temperature [C]->[K]
% T_ISA = T0 + (lambda*hp);                                         % ISA temperature at hp [K]
% dT = T_static - T_ISA;
% FFL = flightdata.lh_engine_FMF.data(i_series1)*(lbs2kg/3600);     % Left fuel flow [lbs/hr]->[kg/s]
% FFR = flightdata.rh_engine_FMF.data(i_series1)*(lbs2kg/3600);     % Right fuel flow [lbs/hr]->[kg/s]
% thrusttable = [round(hp,4) round(mach,4) round(dT,4) round(FFL,4) round(FFR,4)];
% writematrix(thrusttable, 'matlab.dat', 'Delimiter', ' ');


% Compute CLa, CL0, CD0 and e, using thrust.dat generated by thrust.exe
% Assume thrust lies in a/c body x-axis, contribution of tail neglected
% L + T*sin(alpha) = W*cos(theta-alpha)
% T*cos(alpha) = W*sin(theta-alpha) + D
% Weight
ful = flightdata.lh_engine_FU.data(i_series1)*lbs2kg;       % Fuel used of left engine [lbs]->[kg]
fur = flightdata.rh_engine_FU.data(i_series1)*lbs2kg;       % Fuel used of right engine [lbs]->[kg]
W_tot = (m_init-(ful+fur))*g;                               % Total weight at each moment [N]
% Air
TAS = flightdata.Dadc1_tas.data(i_series1)*kts2mps;         % True airspeed [knots]->[m/s]
alpha = deg2rad(flightdata.vane_AOA.data(i_series1));       % AOA [rad]
theta = deg2rad(flightdata.Ahrs1_Pitch.data(i_series1));    % Pitch angle [rad]
hp = flightdata.Dadc1_alt.data(i_series1)*ft2m;             % Pressure altitude [ft]->[m]
p_static = p0*(1+lambda*hp/T0).^(-g/lambda/R);              % Static pressure [Pa]
T_static = 273.15+flightdata.Dadc1_sat.data(i_series1);     % Static temperature [C]->[K]
rho = p_static./T_static/R;                                 % True air density [kg/m^3]
% Thrust
thrust = importdata(strcat(whichone, '_series1_thrust.dat'));
thrust_tot = sum(thrust, 2);                                % Total thrust by both engines [N]
% Aerodynamic forces
L = W_tot.*cos(theta-alpha)-thrust_tot.*sin(alpha);         % Lift [N]
D = thrust_tot.*cos(alpha)-W_tot.*sin(theta-alpha);         % Drag [N]
% aerodynamic coefficietns
alpha = rad2deg(alpha);                                     % AOA [deg]
CL = L./(0.5*rho.*TAS.^2*S_wing);                           % Lift coefficient by definition
linear_CL = polyfit(alpha, CL, 1);                          % Linear regression CL-alpha
CLa = linear_CL(1);                                         % [/deg]
CL0 = linear_CL(2);                                         % CL at aoa=0 []
CD = D./(0.5*rho.*TAS.^2*S_wing);                           % Drag coefficient by definition
linear_CD = polyfit(CL.^2, CD, 1);                          % Linear regression CD-CL^2
e = 1/(pi*A*linear_CD(1));                                  % Oswald factor
CD0 = linear_CD(2);                                         % Zero lift drag coefficient

% Print and plot
disp([round(CLa,4), round(CL0,4), round(CD0,4), round(e,4)])
figure
scatter(alpha, CL); hold on;
plot(alpha, CLa*alpha+CL0);
xlabel('\alpha [deg]'); ylabel('C_L');
figure
scatter(CD, CL); hold on;
plot(CD(1):1e-4:CD(end), sqrt(pi*A*e*((CD(1):1e-4:CD(end))-CD0)));
xlabel('C_D'); ylabel('C_L');
